site_name: Entangled
site_url: https://entangled.github.io

nav:
    - index.md
    - Configuration:
        - markup.md
        - templates.md
    - Hooks:
        - hooks.md
        - quarto_attributes.md
    - Workflows:
        - workflows.md
        - build-hook.md
    - Troubleshooting:
        - git.md
    - Resources:
        - ieee-escience-paper.md
        - manual.md

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - tags
  - bibtex:
     bib_file: "refs.bib"
  - entangled

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.details
  - def_list

theme:
  name: material
  logo: assets/logo.svg
  features:
    - navigation.instant
    - toc.follow
    - toc.integrate
    - content.code.copy
  palette: 
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to system preference

    # Palette toggle for light mode
    - scheme: slate
      primary: pink
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
      media: "(prefers-color-scheme: dark)"

    # Palette toggle for dark mode
    - scheme: default
      primary: pink
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
      media: "(prefers-color-scheme: light)"
